### ISSUE TITLE
Remove online dependency

### ISSUE THREAD

**Issue by JulianWgs** [voila-dashboards/voila-reveal#16]
First I want to give you a huge praise for this amazing idea and project! It's really cool!

Today I held a presentation and I nearly got a heartattack, when the slide formatting didn't work without an internet connection. I got it to work with a mobile hotspot, but I'd spare others the trouble.

To reproduce this error one must clear all cached file of the browser and cut the internet connection. A private Firefox window worked for me.

I'd propose either including or somehow caching the I presume missing reveal.js file.

If that's not viable I'd propose to give at least give a hint in the readme. This can easily lead to some embarrassing moments.

Best regards,
Julian

**Comment by SylvainCorlay** [comment]
@meeseeksdev please migrate to voila-dashboards/voila
