### ISSUE TITLE
Markdown not rendering properly

### ISSUE THREAD

**Issue by JPchico** [voila-dashboards/voila-reveal#17]
Hello!

I was trying to build a set of slides using `voila-reveal==0.02` using some plotly plots and markdown text.

I noticed that not all the markdown calls are being properly rendered, e.g. the header call `#` is not rendered whilst the list call `*` is rendered.
I tried checking with the [voila-reveal-example](https://github.com/mkcor/voila-reveal-example) to see if there was something wrong on my notebook, but the calls were not being rendered in the example either.

This happens when using `voila index.ipynb --template=reveal --VoilaConfiguration.file_whitelist="['.*']" --enable_nbextensions=True`. 

Is there some other instruction that must be passed to ensure that the markdown is properly rendered? 

Thanks!

**Comment by mkcor** [comment]
Hello @JPchico!

Please update `voila-reveal` to the latest version (0.1.1). I'm using it right now and the Markdown is rendered properly.

Let us know how it goes!

**Comment by SylvainCorlay** [comment]
I think that his should be closed as fixed.
