### ISSUE TITLE
Support "rise" notebook template metadata?

### ISSUE THREAD

**Issue by grantjenks** [voila-dashboards/voila-reveal#21]
## Description

RISE supports configuration through notebook metadata (https://rise.readthedocs.io/en/stable/customize.html#notebook-metadata) but for some reason this doesn't work with Voila. Is this supported?

## Reproduce

1. Create a simple notebook.
2. Edit the notebook metadata to include:
`"rise": {"theme": "solarized"},`
3. Render the notebook in Voila.
4. Observe the "solarized" theme is not used.

## Expected behavior

Customization of the Reveal JS presentation is possible with notebook metadata.

## Context

- voila version: Latest
- Operating System and version: Mac OS
- Browser and version: Chrome Latest

**Comment by SylvainCorlay** [comment]
Hey, sorry for not replying earlier.

We definitely support nbconvert metadata for slides and subslides, but rise-specific metadata at the moment.

However, we should definitely look into adding this.

**Comment by SylvainCorlay** [comment]
@meeseeksdev migrate to voila-dashboards/voila

**Comment by SylvainCorlay** [comment]
@meeseeksdev please migrate to voila-dashboards/voila

**Comment by SylvainCorlay** [comment]
@meeseeksdev please migrate to voila-dashboards/voila
