### ISSUE TITLE
Add archive note about voila-reveal being part of core Voila

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila-reveal#23]
### Problem

The `voila-reveal` template was added to the core Voila repo in https://github.com/voila-dashboards/voila/pull/932

### Suggested Improvement

We should document this here in this repo, to inform users of `voila==0.3` they don't need to install `voila-reveal` separately.

**Comment by SylvainCorlay** [comment]
I added a note in the readme about this, and moved the issues to the Voilà GitHub repository.

**Comment by jtpio** [comment]
Nice, thanks!
