### ISSUE TITLE
Document mechanism for how to change slide type

### ISSUE THREAD

**Issue by ned2** [voila-dashboards/voila-reveal#7]
It seems that the way to specify that cell is a `slide` or a `subslide`, is by setting the `slide_type` property within the `slideshow` property of the cell's metadata.   

```json
...
"metadata": {
    "slideshow": {
     "slide_type": "slide"
    }
} 
...
```
I was only able to work this out by looking at the source of the included demo `reveal.ipynb`. It would be great to have this included in documentation to make this discoverable. This tool has the potential to become extremely useful, but this issue I fear is a big barrier to adoption.

**Comment by ned2** [comment]
Further to this, I didn't actually know how to edit cell metadata in Jupyer Lab and only worked out that there is a cell editor in the sidebar after a little bit if googling around. Perhaps this kind o fscreenshot could be helpful?
![Screenshot from 2020-05-17 16-32-07](https://user-images.githubusercontent.com/2831640/82137533-7ffe3200-985c-11ea-915a-a0d19de5adca.png)

**Comment by agoose77** [comment]
For those looking, there is a `cell metadata` section in the `Advanced Tools` panel in the cell toolbar pictured.

**Comment by mkcor** [comment]
Hi @ned2,

You can find this kind of screenshot in this post: https://medium.com/@mjspeck/presenting-code-using-jupyter-notebook-slides-a8a3c3b59d67 (Walkthrough section), which the [announcement post](https://blog.jupyter.org/a-slideshow-template-for-voil%C3%A0-apps-435f67d10b4f) links to. Let me add it to the README!

**Comment by SylvainCorlay** [comment]
Yes, we definitely need to improve this.

**Comment by SylvainCorlay** [comment]
@meeseeksdev please migrate to voila-dashboards/voila
